Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,37 +2,36 @@ version: 2.1
 
 commands:
   destroy-environment:
-    description: Destroy back-end and front-end cloudformation stacks given a workflow ID. 
+    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      workflow_id:
-        type: string 
+      # Add parameter here   
     steps:
       - run:
           name: Destroy environments
-          when: on_fail 
+          when: on_fail
           command: |
-            aws s3 rm s3://udapeople-"${CIRCLE_WORKFLOW_ID}" --recursive
-            aws s3 rb s3://udapeople-"${CIRCLE_WORKFLOW_ID}" --force
-            aws cloudformation delete-stack --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID}"
-            aws cloudformation delete-stack --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID}"    
+            # Your code here
+            exit 1
+
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
-      workflow_id:
-        type: string     
+      # Add parameter here     
     steps:
       - run:
           name: Revert migrations
-          when: on_fail
+          # Add when this will run
           command: |
-            SUCCESS=$(curl -H "token: b3c37955-bc53-449d-88f5-cbfeefbbc634" --request GET https://api.memstash.io/values/migration_<< parameters.workflow_id >>)
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS = 1
             if(( $SUCCESS==1 )); 
             then
-              cd backend
-              npm install
-              npm run migrations:revert
+            #  cd ~/project/backend
+            #  npm install
+            #  Add revert code here. You can find this in the Getting Started section.
               exit 1
             fi
+            
 jobs:
   build-frontend:
     docker:
@@ -44,12 +43,11 @@ jobs:
       - run:
           name: Build front-end
           command: |
-            cd frontend
-            npm i
-            npm run build
+            # Your code here
+            exit 1
       - save_cache:
           paths: [frontend/node_modules]
-          key: frontend-build      
+          key: frontend-build
 
   build-backend:
     docker:
@@ -59,321 +57,212 @@ jobs:
       - restore_cache:
           keys: [backend-build]
       - run:
-          name: Build Back-end 
+          name: Back-end build
           command: |
-             cd backend
-             npm i
-             npm run build
+             # Your code here
+             exit 1
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
 
   test-frontend:
     docker:
-      - image: circleci/node:13.8.0
+      # Docker image here
     steps:
-      - checkout
-      - restore_cache:
-           keys: [frontend-build]
-      - run:
-          name: test-frontend 
-          command: |
-             cd frontend
-             npm i
-             npm run test              
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here
+                
   test-backend:
-      docker:
-        - image: circleci/node:13.8.0
-      steps:
-        - checkout
-        - restore_cache:
-           keys: [backend-build]
-        - run:
-            name: test-backend 
-            command: |
-             cd backend
-             npm i
-             npm run test   
+    docker:
+      # Docker image here
+    steps:
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here
+            
   scan-frontend:
     docker:
-      - image: circleci/node:13.8.0
+      # Docker image here
     steps:
-      - checkout
-      - restore_cache:
-           keys: [frontend-build]
-      - run:
-            name: scan-frontend 
-            command: |
-             cd backend
-             npm i
-             npm audit fix --audit-level=critical --force
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here
+
   scan-backend:
     docker:
-      - image: circleci/node:13.8.0
+      # Docker image here
     steps:
-      - checkout
-      - restore_cache:
-           keys: [backend-build]
-      - run:
-            name: scan-backend 
-            command: |
-             cd backend
-             npm i
-             npm audit fix --audit-level=critical --force  
+      # Checkout code from git
+      # Restore from cache
+      # Your job code here
+
   deploy-infrastructure:
     docker:
-      - image: amazon/aws-cli
+      # Docker image here that supports AWS CLI
     steps:
-      - checkout
-      - run: yum install -y tar 
-      - run: yum install -y gzip
+      # Checkout code from git
       - run:
           name: Ensure back-end infrastructure exists
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
-              --tags project=udapeople \
-               --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID}" \
-               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"  
-            URLS=$(aws ec2 describe-instances --region us-west-2 --query "Reservations[*].Instances[*].PublicIpAddress"   --output text)
-            echo "URLS=$URLS"    
-            echo $URLS >> .circleci/ansible/inventory.txt
-            cat ./.circleci/ansible/inventory.txt
-            curl -H "Content-Type: text/plain" -H "token: 4494694a-4f89-4073-a5a0-00fb827decc6" --request PUT --data "URLS" https://api.memstash.io/values/CIRCLE_WORKFLOW_ID
-      - persist_to_workspace:
-            root: .circleci/ansible
-            paths:
-              - inventory.txt      
+              #--tags project=your-tag \
+              # --stack-name "your back-end stack name with workflow id" \
+              # --parameter-overrides ID="your workflow id"  
+              exit 1
       - run:
           name: Ensure front-end infrastructure exist
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
-              --tags project=udapeople \
-               --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID}" \
-               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"  
-               ARN=$(aws s3 ls | grep udapeople)
-               echo "ARN=$ARN"
-               curl -H "Content-Type: text/plain" -H "token: 4494694a-4f89-4073-a5a0-00fb827decc6" --request PUT --data "$ARN" https://api.memstash.io/values/arn_${CIRCLE_WORKFLOW_ID}
-      
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID}
+              #--tags project=your-tag \
+              # --stack-name "your front-end stack name with workflow id" \
+              # --parameter-overrides ID="your workflow id"  
+              exit 1
+      - run:
+          name: Add back-end ip to ansible inventory
+          command: |
+            # Your code here
+            exit 1
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/.circleci/ansible/inventory.txt
+      # Here's where you will add some code to rollback on failure      
 
-      - revert-migrations:
-          workflow_id: ${CIRCLE_WORKFLOW_ID}  
-
-      
   configure-infrastructure:
     docker:
-      - image: python:3.7-alpine3.11
+      # Docker image here that supports Ansible
     steps:
-      - checkout
-      - add_ssh_keys:
-          fingerprints: ['4c:d2:f4:f5:ff:ec:95:60:eb:2f:ec:d7:33:79:1c:b9'] #['69:fe:8c:6a:bb:be:56:11:a7:e8:4d:27:b9:59:6d:90'] #["2c:96:88:f7:91:5d:4f:3d:8e:41:d8:bd:46:c0:ee:7e"]
-      - attach_workspace:
-          at: .circleci/ansible
+      # Checkout code from git
+      # Add ssh keys with fingerprint
+      # attach workspace
       - run:
           name: Install dependencies
           command: |
-            apk add --update ansible    
+            # Your code here
+            exit 1
       - run:
           name: Configure server
           command: |
-            cat ./.circleci/ansible/inventory.txt
-            cd .circleci/ansible/    
-            ansible-playbook -i inventory.txt configure-server.yml
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID}  
-      - revert-migrations:
-          workflow_id: ${CIRCLE_WORKFLOW_ID}    
+            # Your code here
+            exit 1
+      # Here's where you will add some code to rollback on failure      
 
   run-migrations:
     docker:
-      - image: circleci/node:13.8.0
+      # Docker image here that supports NodeJS
     steps:
-      - checkout
-      - restore_cache:
-          keys: [build-backend]
+      # Checkout code from git
       - run:
           name: Run migrations
           command: |
-            cd backend
-            npm install
-            npm run migrations > migration_${CIRCLE_WORKFLOW_ID}.txt
-            cat migration_${CIRCLE_WORKFLOW_ID}.txt
+            # Your code here
+            exit 1
       - run:
           name: Send migration results to memstash
           command: |
-            cd backend
-            cat migration_${CIRCLE_WORKFLOW_ID}.txt
-            result=0
-            if grep -q "has been executed successfully" migration_${CIRCLE_WORKFLOW_ID}.txt
-            then
-              result=1
-            fi
-            curl -H "Content-Type: text/plain" \
-            -H "token: migration_${CIRCLE_WORKFLOW_ID}" \
-            --request PUT \
-            --data ${result} https://api.memstash.io/values/migration
-            echo ${result}
-            
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID} 
-      - revert-migrations:
-          workflow_id: ${CIRCLE_WORKFLOW_ID}
+            # Your code here
+            exit 1
+     # Here's where you will add some code to rollback on failure      
 
   deploy-frontend:
     docker:
-      - image: amazon/aws-cli
+      # Docker image here that supports AWS CLI
     steps:
-      - checkout
+      # Checkout code from git
       - run:
           name: Install dependencies
           command: |
-            yum -y install tar gzip 
-            curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
-            yum -y install nodejs
+            # your code here
       - run:
           name: Get backend url
           command: |
-            export BACKEND_IP=$(aws ec2 describe-instances \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
+            # your code here
             export API_URL="http://${BACKEND_IP}:3030"
-            echo API_URL="http://${BACKEND_IP}:3030" >> "frontend/.env"
-            cat frontend/.env
+            echo "${API_URL}"
       - run:
           name: Deploy frontend objects
-          command: |  
-            npm install webpack-dev-server -g
-            cd frontend
-            npm install
-            npm run build
-            aws s3 cp ./dist s3://udapeople-${CIRCLE_WORKFLOW_ID} --recursive
-     # - destroy-environment:
-      #    workflow_id: ${CIRCLE_WORKFLOW_ID}    
-      #- revert-migrations:
-       #   workflow_id: ${CIRCLE_WORKFLOW_ID}    
+          command: |
+            # your code here
+      # Here's where you will add some code to rollback on failure      
                     
   deploy-backend:
     docker:
-      - image: python:3.7-alpine3.11
+      # Docker image here that supports Ansible
     steps:
-      - checkout
-      - add_ssh_keys:
-          fingerprints:
-            - "4c:d2:f4:f5:ff:ec:95:60:eb:2f:ec:d7:33:79:1c:b9"
-      - attach_workspace:
-          at: .circleci/ansible
-      - run:
-          name: Install AWS CLI
-          command: pip3 install awscli
-      - run:
-          name: Install ansible
-          command: |
-            apk add --update ansible
-            ansible-galaxy install weareinteractive.environment
-      - run:
-          name: Install curl
-          command: apk add curl
-      - run:
-          name: Install Open SSH
-          command: apk add openssh-client
-      - run:
-          name: Check folders
-          command: |
-            echo $(pwd)
-          #  ls /root/project/backend
-      - run:
-          name: Configure backend server
-          command: |
-            tar -C backend -czvf artifact.tar.gz .
-            cat backend/.env
-            cd .circleci/ansible/
-            export ANSIBLE_HOST_KEY_CHECKING=False
-            ansible-playbook -i inventory.txt deploy-backend.yml
-            
-      #- destroy-environment:
-       #   workflow_id: ${CIRCLE_WORKFLOW_ID}   
-      #- revert-migrations:
-       #   workflow_id: ${CIRCLE_WORKFLOW_ID}    
-
-  smoke-test:
-    docker:
-      - image: python:3.7-alpine3.11 
-    steps:
-      - checkout
+      # Checkout code from git
+      # Add ssh keys with fingerprint
+      # attach workspace
       - run:
           name: Install dependencies
           command: |
-            apk add --update curl
-            pip install awscli
+            # your code here
       - run:
-          name: Get backend url and smoke test
-          no_output_timeout: 30m
+          name: Deploy backend
           command: |
-              BACKEND_URL=$(aws ec2 describe-instances \
-              --filters Name=instance-state-name,Values=running \
-              --query 'Reservations[*].Instances[*].PublicDnsName' \
-              --output text)
-               echo "${BACKEND_URL}"
-               curl "http://${BACKEND_URL}:3030/api/status"
-              
+            # your code here
+      # Here's where you will add some code to rollback on failure  
+
+  smoke-test:
+    docker:
+      # Lightweight Docker image 
+    steps:
+      # Checkout code from git
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+      - run:
+          name: Get backend url
+          command: |
+            # your code here
+      - run:
+          name: Backend smoke test.
+          command: |
+            # your code here
       - run:
           name: Frontend smoke test.
           command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website-us-west-2.amazonaws.com"
-            if curl -s ${URL} | grep "Welcome"
-            then
-              return 0
-            else
-              return 1
-            fi
-     # - destroy-environment:
-      #    workflow_id: ${CIRCLE_WORKFLOW_ID}  
-      #- revert-migrations:
-       #   workflow_id: ${CIRCLE_WORKFLOW_ID}    
+            # your code here
+      # Here's where you will add some code to rollback on failure  
 
   cloudfront-update:
     docker:
-      - image: amazon/aws-cli
+      # Docker image here that supports AWS CLI
     steps:
-      - checkout
+      # Checkout code from git
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
       - run:
           name: Update cloudfront distribution
           command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/cloudfront.yml \
-              --stack-name udapeople-cloudfront-${CIRCLE_WORKFLOW_ID} \
-              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID}" \
-              --tags project=udapeople-cloudfront
-     # - destroy-environment:
-      #    workflow_id: ${CIRCLE_WORKFLOW_ID}   
-     # - revert-migrations:
-      #    workflow_id: ${CIRCLE_WORKFLOW_ID}
+            # your code here
+      # Here's where you will add some code to rollback on failure  
 
-  cleanup:
+cleanup:
     docker:
-      - image: amazon/aws-cli
+      # Docker image here
     steps:
-      - checkout
+      # Checkout code from git
       - run:
-          name: old stack workflow id / remove old stack and files
+          name: Get old stack workflow id
           command: |
-            export OldWorkflowID=$(aws cloudformation \
-             list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-             --no-paginate --output text)      
-            
-            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
-            --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
-            echo Old Workflow Id: "${OldWorkflowID}"
-            echo Current Workflow Id: "${CIRCLE_WORKFLOW_ID}"
+            # your code here
+            export OldWorkflowID="the id here"
+            export STACKS=[] #put the list of stacks here
+      - run:
+          name: Remove old stacks and files
+          command: |
             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-            then 
-              aws s3 rb s3://udapeople-${OldWorkflowID} --force
-              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+            then
+              # your code here
             fi
+            
+
 workflows:
   default:
     jobs:
@@ -386,20 +275,23 @@ workflows:
       - scan-backend:
           requires: [build-backend]
       - scan-frontend:
-          requires: [build-frontend]    
+          requires: [build-frontend]
       - deploy-infrastructure:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          filters:
+            branches:
+              only: [test-feature-branch]
       - configure-infrastructure:
-          requires: [deploy-infrastructure]        
+          requires: [deploy-infrastructure]
       - run-migrations:
-          requires: [configure-infrastructure]    
+          requires: [configure-infrastructure]
       - deploy-frontend:
           requires: [run-migrations]
       - deploy-backend:
-          requires: [run-migrations]    
+          requires: [run-migrations]
       - smoke-test:
-          requires: [deploy-backend, deploy-frontend]    
+          requires: [deploy-backend, deploy-frontend]
       - cloudfront-update:
-          requires: [smoke-test]   
-      #- cleanup:
-         # requires: [cloudfront-update] 
+          requires: [smoke-test]
+      - cleanup:
+          requires: [cloudfront-update]
